# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl)

from . import (
    ceppp_suite_crm_assistance_mob,
    ceppp_suite_crm_chapitre_maladie,
    ceppp_suite_crm_commentaires_recruteur,
    ceppp_suite_crm_competences_pp,
    ceppp_suite_crm_competences_ppc,
    ceppp_suite_crm_competences_pr,
    ceppp_suite_crm_deplacements,
    ceppp_suite_crm_disponibilites,
    ceppp_suite_crm_domaine_soin_pa,
    ceppp_suite_crm_emploi_perso,
    ceppp_suite_crm_entrevues,
    ceppp_suite_crm_exp_patient_partenaire,
    ceppp_suite_crm_formation,
    ceppp_suite_crm_habiletes_pp,
    ceppp_suite_crm_hopital,
    ceppp_suite_crm_langue_parlee,
    ceppp_suite_crm_maladie,
    ceppp_suite_crm_med_2,
    ceppp_suite_crm_partenariats,
    ceppp_suite_crm_patients,
    ceppp_suite_crm_perspective_patient,
    ceppp_suite_crm_preferences,
    ceppp_suite_crm_region_admin,
    ceppp_suite_crm_role_pp,
)
