from odoo import _, api, fields, models


class CepppSuiteCrmPerspectivePatient(models.Model):
    _name = "ceppp.suite_crm.perspective_patient"
    _description = "ceppp_suite_crm_perspective_patient"
    _rec_name = "adresse_perso_city"

    adresse_perso_city = fields.Char(string="Ville")

    adresse_perso = fields.Char(string="Adresse")

    adresse_perso_country = fields.Char(string="Pays")

    adresse_perso_postalcode = fields.Char(string="Code postal")

    adresse_perso_state = fields.Char(string="Province")

    conflit_interet = fields.Selection(
        selection=[("oui", "Oui"), ("non", "Non")],
        string="Conflits d'intérêt",
    )

    conflit_interet_detail = fields.Text(string="Lesquels")

    descr_exp = fields.Text(string="Description de l'expérience")

    disponibilites = fields.Selection(
        selection=[
            ("matin", "Matin"),
            ("apresmidi", "Après-midi"),
            ("soir", "Soir"),
            ("fins_de_semaine", "Fins de semaine"),
            ("jours", "Jours"),
        ],
        string="Disponibilités",
    )

    domaine_soin = fields.Selection(
        selection=[
            ("allergologie_ou_l_immunologie", "Allergologie ou l'immunologie"),
            ("anesthesiologie", "Anesthésiologie"),
            ("andrologie", "Andrologie"),
            ("cardiologie", "Cardiologie"),
            ("chirurgie_cardiaque", "Chirurgie cardiaque"),
            (
                "chirurgie_esthetique_plastique_et_reconstructive",
                "Chirurgie esthétique plastique et reconstructive",
            ),
            ("chirurgie_generale", "Chirurgie générale"),
            ("chirurgie_maxillo_faciale", "Chirurgie maxillo-faciale"),
            ("chirurgie_pediatrique", "Chirurgie pédiatrique"),
            ("chirurgie_thoracique", "Chirurgie thoracique"),
            ("chirurgie_vasculaire", "Chirurgie vasculaire"),
            ("neurochirurgie", "Neurochirurgie"),
            ("dermatologie", "Dermatologie"),
            ("endocrinologie", "Endocrinologie"),
            ("gastro_enterologie", "Gastro-entérologie"),
            ("geriatrie", "Gériatrie"),
            ("gynecologie", "Gynécologie"),
            ("hematologie", "Hématologie"),
            ("hepatologie", "Hépatologie"),
            ("infectiologie", "Infectiologie"),
            ("medecine_aigue", "Médecine aiguë"),
            ("medecine_du_travail", "Médecine du travail"),
            ("medecine_generale", "Médecine générale"),
            ("medecine_interne", "Médecine interne"),
            ("medecine_nucleaire", "Médecine nucléaire"),
            ("medecine_palliative", "Médecine palliative"),
            ("medecine_physique", "Médecine physique"),
            ("medecine_preventive", "Médecine préventive"),
            ("neonatologie", "Néonatologie"),
            ("nephrologie", "Néphrologie"),
            ("neurologie", "Neurologie"),
            ("odontologie", "Odontologie"),
            ("oncologie", "Oncologie"),
            ("obstetrique", "Obstétrique"),
            ("ophtalmologie", "Ophtalmologie"),
            ("orthopedie", "Orthopédie"),
            ("oto_rhino_laryngologie", "Oto-rhino-laryngologie"),
            ("pediatrie", "Pédiatrie"),
            ("pneumologie", "Pneumologie"),
            ("psychiatrie", "Psychiatrie"),
            ("radiologie", "Radiologie"),
            ("radiotherapie", "Radiothérapie"),
            ("rhumatologie", "Rhumatologie"),
            ("urologie", "Urologie"),
        ],
        string="Je suis ou j'ai été suivi(e) dans les spécialités suivantes",
    )

    domaine_soin_pa = fields.Selection(
        selection=[
            ("allergologie_ou_l_immunologie", "Allergologie ou l'immunologie"),
            ("anesthesiologie", "Anesthésiologie"),
            ("andrologie", "Andrologie"),
            ("cardiologie", "Cardiologie"),
            ("chirurgie_cardiaque", "Chirurgie cardiaque"),
            (
                "chirurgie_esthetique_plastique_et_reconstructive",
                "Chirurgie esthétique plastique et reconstructive",
            ),
            ("chirurgie_generale", "Chirurgie générale"),
            ("chirurgie_maxillo_faciale", "Chirurgie maxillo-faciale"),
            ("chirurgie_pediatrique", "Chirurgie pédiatrique"),
            ("chirurgie_thoracique", "Chirurgie thoracique"),
            ("chirurgie_vasculaire", "Chirurgie vasculaire"),
            ("neurochirurgie", "Neurochirurgie"),
            ("dermatologie", "Dermatologie"),
            ("endocrinologie", "Endocrinologie"),
            ("gastro_enterologie", "Gastro-entérologie"),
            ("geriatrie", "Gériatrie"),
            ("gynecologie", "Gynécologie"),
            ("hematologie", "Hématologie"),
            ("hepatologie", "Hépatologie"),
            ("infectiologie", "Infectiologie"),
            ("medecine_aigue", "Médecine aiguë"),
            ("medecine_du_travail", "Médecine du travail"),
            ("medecine_generale", "Médecine générale"),
            ("medecine_interne", "Médecine interne"),
            ("medecine_nucleaire", "Médecine nucléaire"),
            ("medecine_palliative", "Médecine palliative"),
            ("medecine_physique", "Médecine physique"),
            ("medecine_preventive", "Médecine préventive"),
            ("neonatologie", "Néonatologie"),
            ("nephrologie", "Néphrologie"),
            ("neurologie", "Neurologie"),
            ("odontologie", "Odontologie"),
            ("oncologie", "Oncologie"),
            ("obstetrique", "Obstétrique"),
            ("ophtalmologie", "Ophtalmologie"),
            ("orthopedie", "Orthopédie"),
            ("oto_rhino_laryngologie", "Oto-rhino-laryngologie"),
            ("pediatrie", "Pédiatrie"),
            ("pneumologie", "Pneumologie"),
            ("psychiatrie", "Psychiatrie"),
            ("radiologie", "Radiologie"),
            ("radiotherapie", "Radiothérapie"),
            ("rhumatologie", "Rhumatologie"),
            ("urologie", "Urologie"),
        ],
        string="Spécialités de soins",
    )

    duree_experience = fields.Char(string="Durée d'expérience (Années / Mois)")

    etabl_prem_ligne = fields.Many2one(
        comodel_name="ceppp.suite_crm.hopital",
        string="Établissement de première ligne",
    )

    etabl_prem_ligne_pa = fields.Char(string="Établissement de première ligne")

    etabl_sante = fields.Many2one(
        comodel_name="ceppp.suite_crm.hopital",
        string="Établissement de santé principal",
    )

    etabl_sante_pa = fields.Char(string="Établissement de santé principal")

    exp_decision = fields.Selection(
        selection=[
            ("oui", "Oui"),
            ("non", "Non"),
            ("ne_sait_pas", "Ne sait pas"),
        ],
        string="Expérience prise de décision relative à ses soins médicaux",
    )

    exp_sante = fields.Selection(
        selection=[("oui", "Oui"), ("non", "Non")],
        string="Expérience professionnelle dans le milieu de la santé",
    )

    exp_sante_detail = fields.Text(string="Précisions")

    experience_maladie = fields.Text(string="Expérience maladie")

    experience_maladie_pa = fields.Text(string="Expérience comme pair aidant")

    experience_maladie_proche = fields.Text(
        string="Expérience maladie proche",
        help="What is your family member's experience with illness?",
    )

    formation_date = fields.Date(string="Date de formation")

    formation_oui = fields.Char(string="Si oui, laquelle")

    formation_pp = fields.Selection(
        selection=[("oui", "Oui"), ("non", "Non")],
        string="Formation suivie sur le partenariat patient",
    )

    formation_qui = fields.Char(string="Formation par qui")

    maladie_rare_details = fields.Text(string="Maladie rare")

    med_1 = fields.Text(string="Médicaments")

    med_2 = fields.Selection(
        selection=[
            ("accolate", "Accolate"),
            ("accuneb", "Accuneb"),
            ("accuretic", "Accuretic"),
            ("aceon", "Aceon"),
            ("aclovate", "Aclovate"),
            ("actigall", "Actigall"),
            ("actiq", "Actiq"),
            ("adalat_cc", "Adalat CC"),
            ("adderall", "Adderall"),
            ("adderall_xr", "Adderall XR"),
            ("adipex_p", "Adipex-P"),
            ("agrylin", "Agrylin"),
            ("aldactazide", "Aldactazide"),
            ("aldactone", "Aldactone"),
            ("aldara", "Aldara"),
            ("allegra", "Allegra"),
            ("alphagan_p", "Alphagan P"),
            ("altace", "Altace"),
            ("amaryl", "Amaryl"),
            ("ambien", "Ambien"),
            ("ambien_cr", "Ambien CR"),
            ("amerge", "Amerge"),
            ("anafranil", "Anafranil"),
            ("anaprox", "Anaprox"),
            ("antivert", "Antivert"),
            ("aralen", "Aralen"),
            ("arava", "Arava"),
            ("aricept", "Aricept"),
            ("aricept_odt", "Aricept ODT"),
            ("astelin", "Astelin"),
            ("ativan", "Ativan"),
            ("atrovent_nasal spray", "Atrovent Nasal Spray"),
            ("augmentin", "Augmentin"),
            ("augmentin_xr", "Augmentin XR"),
            ("axid", "Axid"),
            ("aygestin", "Aygestin"),
            ("azulfidine", "Azulfidine"),
            ("azulfidine_en_tabs", "Azulfidine EN-TABS"),
            ("bactroban", "Bactroban"),
            ("bentyl", "Bentyl"),
            ("benzac_ac", "Benzac AC"),
            ("benzamycin", "Benzamycin"),
            ("betagan", "Betagan"),
            ("betapace_af", "Betapace AF"),
            ("biaxin", "Biaxin"),
            ("biaxin_xl", "Biaxin XL"),
            ("bleph_10", "Bleph-10"),
            ("bontril", "Bontril"),
            ("brethine", "Brethine"),
            ("brevicon", "Brevicon"),
            ("cafergot", "Cafergot"),
            ("calan", "Calan"),
            ("calan_sr", "Calan SR"),
            ("carafate", "Carafate"),
            ("cardizem", "Cardizem"),
            ("cardizem_cd", "Cardizem CD"),
            ("cardizem_la", "Cardizem LA"),
            ("cardura", "Cardura"),
            ("cataflam", "Cataflam"),
            ("catapres", "Catapres"),
            ("ceftin", "Ceftin"),
            ("cellcept", "Cellcept"),
            ("ciloxan", "Ciloxan"),
            ("cipro", "Cipro"),
            ("claritin", "Claritin"),
            ("cleocin", "Cleocin"),
            ("cleocin_t", "Cleocin T"),
            ("cleocin_vaginal_cream", "Cleocin Vaginal Cream"),
            ("climara", "Climara"),
            ("clinoril", "Clinoril"),
            ("clomid", "Clomid"),
            ("clozaril", "Clozaril"),
            ("colazal", "Colazal"),
            ("colestid", "Colestid"),
            ("condylox", "Condylox"),
            ("copegus", "Copegus"),
            ("cordarone", "Cordarone"),
            ("coreg", "Coreg"),
            ("corgard", "Corgard"),
            ("cortef", "Cortef"),
            ("corzide", "Corzide"),
            ("cosopt", "Cosopt"),
            ("coumadin", "Coumadin"),
            ("cozaar", "Cozaar"),
            ("cutivate", "Cutivate"),
            ("cyclogyl", "Cyclogyl"),
            ("cytomel", "Cytomel"),
            ("cytotec", "Cytotec"),
            ("cytovene", "Cytovene"),
            ("dantrium", "Dantrium"),
            ("daypro", "Daypro"),
            ("ddavp", "Ddavp"),
            ("demadex", "Demadex"),
            ("demerol", "Demerol"),
            ("depakene", "Depakene"),
            ("depakote", "Depakote"),
            ("depakote_er", "Depakote ER"),
            ("depakote_sprinkles", "Depakote SPRINKLES"),
            ("depo_provera", "Depo-PROVERA"),
            ("desogen", "Desogen"),
            ("desowen", "Desowen"),
            ("dexedrine", "Dexedrine"),
            ("dexedrine_spansule", "Dexedrine SPANSULE"),
            ("d.H.E. 45", "D.H.E. 45"),
            ("diabeta", "Diabeta"),
            ("diamox_sequels", "Diamox SEQUELS"),
            ("differin", "Differin"),
            ("diflucan", "Diflucan"),
            ("dilacor_xr", "Dilacor XR"),
            ("dilantin", "Dilantin"),
            ("dilaudid", "Dilaudid"),
            ("diprolene_af", "Diprolene AF"),
            ("diprolene_gel_lotion_oint", "Diprolene gel / lotion / oint"),
            ("ditropan_xl", "Ditropan XL"),
            ("donnatal", "Donnatal"),
            ("drisdol", "Drisdol"),
            ("duoneb", "Duoneb"),
            ("duragesic", "Duragesic"),
            ("dyazide", "Dyazide"),
            ("ec_naprosyn", "Ec-NAPROSYN"),
            ("effexor_xr", "Effexor XR"),
            ("efudex", "Efudex"),
            ("eldepryl", "Eldepryl"),
            ("eldopaque_forte", "Eldopaque FORTE"),
            ("elocon", "Elocon"),
            ("emla", "Emla"),
            ("esgic", "Esgic"),
            ("esgic_plus", "Esgic-PLUS"),
            ("estrace", "Estrace"),
            ("estrostep_fe", "Estrostep FE"),
            ("exelon", "Exelon"),
            ("famvir", "Famvir"),
            ("feldene", "Feldene"),
            ("fioricet", "Fioricet"),
            ("fiorinal", "Fiorinal"),
            ("flagyl", "Flagyl"),
            ("flagyl_375", "Flagyl 375"),
            ("flagyl_er", "Flagyl ER"),
            ("flarex", "Flarex"),
            ("flexeril", "Flexeril"),
            ("flomax", "Flomax"),
            ("flonase", "Flonase"),
            ("flumadine", "Flumadine"),
            ("fml", "Fml"),
            ("focalin", "Focalin"),
            ("foltx", "Foltx"),
            ("fosamax", "Fosamax"),
            ("glucophage", "Glucophage"),
            ("glucophage_xr", "Glucophage XR"),
            ("glucotrol", "Glucotrol"),
            ("glucovance", "Glucovance"),
            ("glynase", "Glynase"),
            ("halcion", "Halcion"),
            ("hydrea", "Hydrea"),
            ("hyzaar", "Hyzaar"),
            ("imdur", "Imdur"),
            ("imitrex", "Imitrex"),
            ("imuran", "Imuran"),
            ("inderal_la", "Inderal LA"),
            ("inspra", "Inspra"),
            ("isoptin_sr", "Isoptin SR"),
            ("isordil", "Isordil"),
            ("keflex", "Keflex"),
            ("keppra", "Keppra"),
            ("kerlone", "Kerlone"),
            ("klaron", "Klaron"),
            ("klonopin", "Klonopin"),
            ("k_lor_20", "K-LOR 20"),
            ("k_tab", "K-TAB"),
            ("kytril", "Kytril"),
            ("lac_hydrin", "Lac-HYDRIN"),
            ("lamictal", "Lamictal"),
            ("lamisil", "Lamisil"),
            ("lanoxin", "Lanoxin"),
            ("lasix", "Lasix"),
            ("levbid", "Levbid"),
            ("levsin", "Levsin"),
            ("lithobid", "Lithobid"),
            ("lo_OVRAL", "Lo / OVRAL"),
            ("locoid", "Locoid"),
            ("loestrin_1.5_30", "Loestrin 1.5 / 30"),
            ("loestrin_fe_1_20", "Loestrin FE 1 / 20"),
            ("loestrin_fe_1.5_30", "Loestrin FE 1.5 / 30"),
            ("lomotil", "Lomotil"),
            ("lopid", "Lopid"),
            ("lopressor", "Lopressor"),
            ("loprox", "Loprox"),
            ("lorcet", "Lorcet"),
            ("lortab", "Lortab"),
            ("lotensin", "Lotensin"),
            ("lotensin_hct", "Lotensin HCT"),
            ("lotrel", "Lotrel"),
            ("loxitane", "Loxitane"),
            ("luride", "Luride"),
            ("luride_lozi_tabs", "Luride LOZI-TABS"),
            ("lustra", "Lustra"),
            ("macrobid", "Macrobid"),
            ("macrodantin", "Macrodantin"),
            ("mavik", "Mavik"),
            ("maxidone", "Maxidone"),
            ("maxitrol", "Maxitrol"),
            ("maxzide", "Maxzide"),
            ("maxzide_25", "Maxzide-25"),
            ("medrol", "Medrol"),
            ("megace", "Megace"),
            ("mestinon", "Mestinon"),
            ("metadate_er", "Metadate ER"),
            ("metaglip", "Metaglip"),
            ("metrocream", "Metrocream"),
            ("metrolotion", "Metrolotion"),
            ("metrogel_vaginal", "Metrogel-VAGINAL"),
            ("mevacor", "Mevacor"),
            ("miacalcin_nasal_spray", "Miacalcin nasal spray"),
            ("midrin", "Midrin"),
            ("minipress", "Minipress"),
            ("minocin", "Minocin"),
            ("miralax", "Miralax"),
            ("mirapex", "Mirapex"),
            ("mircette", "Mircette"),
            ("mobic", "Mobic"),
            ("modicon", "Modicon"),
            ("monodox", "Monodox"),
            ("motrin", "Motrin"),
            ("ms_contin", "Ms CONTIN"),
            ("myambutol", "Myambutol"),
            ("mycelex", "Mycelex"),
            ("mysoline", "Mysoline"),
            ("naprosyn", "Naprosyn"),
            ("navane", "Navane"),
            ("neo_synephrine", "Neo-SYNEPHRINE"),
            ("neoral", "Neoral"),
            ("neosporin", "Neosporin"),
            ("neurontin", "Neurontin"),
            ("nimotop", "Nimotop"),
            ("niravam", "Niravam"),
            ("nitro_dur", "Nitro-DUR"),
            ("nizoral_shampoo", "Nizoral SHAMPOO"),
            ("nordette", "Nordette"),
            ("norinyl_1_35", "Norinyl 1+35"),
            ("norinyl_1_50", "Norinyl 1+50"),
            ("norpace", "Norpace"),
            ("norpramin", "Norpramin"),
            ("nor_qd", "Nor-QD"),
            ("norvasc", "Norvasc"),
            ("nulytely", "Nulytely"),
            ("ocuflox", "Ocuflox"),
            ("olux", "Olux"),
            ("opana", "Opana"),
            ("optipranolol", "Optipranolol"),
            ("orapred", "Orapred"),
            ("ortho_cept", "Ortho-CEPT"),
            ("ortho_cyclen", "Ortho-CYCLEN"),
            ("ortho_micronor", "Ortho MICRONOR"),
            ("ortho_novum_1_35", "Ortho-NOVUM 1 / 35"),
            ("ortho_novum_7_7_7", "Ortho-NOVUM 7 / 7 / 7"),
            ("ortho_tri_cyclen", "Ortho TRI-CYCLEN"),
            ("ovcon_35", "Ovcon 35"),
            ("ovide", "Ovide"),
            ("oxandrin", "Oxandrin"),
            ("pacerone", "Pacerone"),
            ("pamelor", "Pamelor"),
            ("pamine", "Pamine"),
            ("pamine_forte", "Pamine FORTE"),
            ("parafon_forte_dsc", "Parafon FORTE DSC"),
            ("parcopa", "Parcopa"),
            ("parlodel", "Parlodel"),
            ("parnate", "Parnate"),
            ("paxil", "Paxil"),
            ("paxil_cr", "Paxil CR"),
            ("pediapred", "Pediapred"),
            ("pepcid", "Pepcid"),
            ("percocet", "Percocet"),
            ("percodan", "Percodan"),
            ("peridex", "Peridex"),
            ("periostat", "Periostat"),
            ("persantine", "Persantine"),
            ("phoslo", "Phoslo"),
            ("plaquenil", "Plaquenil"),
            ("plexion", "Plexion"),
            ("polytrim", "Polytrim"),
            ("ponstel", "Ponstel"),
            ("pravachol", "Pravachol"),
            ("pred_forte", "Pred FORTE"),
            ("prelone", "Prelone"),
            ("prevacid", "Prevacid"),
            ("prevacid_solutabs", "Prevacid SOLUTABS"),
            ("prilosec", "Prilosec"),
            ("prinivil", "Prinivil"),
            ("prinzide", "Prinzide"),
            ("procardia_xl", "Procardia XL"),
            ("proctocort", "Proctocort"),
            ("proctocream_hc_2.5", "Proctocream-HC 2.5%"),
            ("proscar", "Proscar"),
            ("prosom", "Prosom"),
            ("protonix", "Protonix"),
            ("provera", "Provera"),
            ("prozac", "Prozac"),
            ("prozac_weekly", "Prozac WEEKLY"),
            ("pulmicort_respules", "Pulmicort RESPULES"),
            ("pyridium", "Pyridium"),
            ("questran", "Questran / QUESTRAN LIGHT"),
            ("razadyne", "Razadyne"),
            ("razadyne_er", "Razadyne ER"),
            ("rebetol", "Rebetol"),
            ("reglan", "Reglan"),
            ("remeron", "Remeron"),
            ("remeron_soltab", "Remeron SOLTAB"),
            ("requip", "Requip"),
            ("restoril", "Restoril"),
            ("retin_a", "Retin-A"),
            ("retrovir", "Retrovir"),
            ("revia", "Revia"),
            ("rifadin", "Rifadin"),
            ("risperdal", "Risperdal"),
            ("risperdal_m_tab", "Risperdal M-TAB"),
            ("ritalin", "Ritalin"),
            ("ritalin_sr", "Ritalin-SR"),
            ("robaxin", "Robaxin"),
            ("rocaltrol", "Rocaltrol"),
            ("rowasa", "Rowasa"),
            ("roxicodone", "Roxicodone"),
            ("rythmol", "Rythmol"),
            ("rythmol_sr", "Rythmol SR"),
            ("salagen", "Salagen"),
            ("sanctura", "Sanctura"),
            ("seasonale", "Seasonale"),
            ("sectral", "Sectral"),
            ("selsun", "Selsun"),
            ("septra", "Septra"),
            ("septra_ds", "Septra DS"),
            ("silvadene", "Silvadene"),
            ("sinemet", "Sinemet"),
            ("sinemet_cr", "Sinemet CR"),
            ("skelaxin", "Skelaxin"),
            ("soma", "Soma"),
            ("sonata", "Sonata"),
            ("sporanox", "Sporanox"),
            ("starlix", "Starlix"),
            ("sular", "Sular"),
            ("synthroid", "Synthroid"),
            ("tambocor", "Tambocor"),
            ("tapazole", "Tapazole"),
            ("tarka", "Tarka"),
            ("tegretol", "Tegretol"),
            ("tegretol_xr", "Tegretol XR"),
            ("temovate", "Temovate"),
            ("tenex", "Tenex"),
            ("tenoretic", "Tenoretic"),
            ("tenormin", "Tenormin"),
            ("tenuate", "Tenuate"),
            ("terazol_3", "Terazol 3"),
            ("terazol_7", "Terazol 7"),
            ("tessalon", "Tessalon"),
            ("tiazac", "Tiazac"),
            ("tigan_caps", "Tigan caps"),
            ("timoptic", "Timoptic"),
            ("timoptic_ocudose", "Timoptic OCUDOSE"),
            ("timoptic_xe", "Timoptic-XE"),
            ("tobradex", "Tobradex"),
            ("tobrex", "Tobrex"),
            ("tofranil", "Tofranil"),
            ("tofranil_pm", "Tofranil PM"),
            ("tolectin", "Tolectin"),
            ("topamax", "Topamax"),
            ("topicort", "Topicort"),
            ("toprol_xl", "Toprol-XL"),
            ("tranxene_t_tab", "Tranxene T-TAB"),
            ("triaz", "Triaz"),
            ("trileptal", "Trileptal"),
            ("tri_norinyl", "Tri-NORINYL"),
            ("trusopt", "Trusopt"),
            ("tussionex", "Tussionex"),
            ("tylenol", "Tylenol WITH CODEINE"),
            ("tylox", "Tylox"),
            ("ultram", "Ultram"),
            ("ultravate", "Ultravate"),
            ("uniretic", "Uniretic"),
            ("univasc", "Univasc"),
            ("urso", "Urso"),
            ("valium", "Valium"),
            ("valtrex", "Valtrex"),
            ("vaseretic", "Vaseretic"),
            ("vasotec", "Vasotec"),
            ("venlafaxine_er", "Venlafaxine ER"),
            ("verelan_pm", "Verelan PM"),
            ("vibramycin", "Vibramycin"),
            ("vicodin", "Vicodin"),
            ("vicodin_es", "Vicodin ES"),
            ("vicoprofen", "Vicoprofen"),
            ("videx_ec", "Videx EC"),
            ("viroptic", "Viroptic"),
            ("vistaril", "Vistaril"),
            ("vivactil", "Vivactil"),
            ("voltaren_ophthalmic", "Voltaren OPHTHALMIC"),
            ("voltaren_xr", "Voltaren-XR"),
            ("vospire_er", "Vospire ER"),
            ("wellbutrin", "Wellbutrin"),
            ("wellbutrin_sr", "Wellbutrin SR"),
            ("wellbutrin_xl", "Wellbutrin XL"),
            ("westcort", "Westcort"),
            ("xanax", "Xanax"),
            ("xanax_xr", "Xanax XR"),
            ("xyzal", "Xyzal"),
            ("yasmin", "Yasmin"),
            ("yaz", "Yaz"),
            ("zanaflex", "Zanaflex"),
            ("zantac", "Zantac"),
            ("zarontin", "Zarontin"),
            ("zaroxolyn", "Zaroxolyn"),
            ("zegerid", "Zegerid"),
            ("zerit", "Zerit"),
            ("zestoretic", "Zestoretic"),
            ("zestril", "Zestril"),
            ("ziac", "Ziac"),
            ("zithromax", "Zithromax"),
            ("zocor", "Zocor"),
            ("zofran", "Zofran"),
            ("zoloft", "Zoloft"),
            ("zonegran", "Zonegran"),
            ("zovirax", "Zovirax"),
            ("zyban", "Zyban"),
            ("zyloprim", "Zyloprim"),
            ("zyrtec", "Zyrtec"),
        ],
        string="Médicaments #2",
    )

    med_3 = fields.Selection(
        selection=[
            ("accolate", "Accolate"),
            ("accuneb", "Accuneb"),
            ("accuretic", "Accuretic"),
            ("aceon", "Aceon"),
            ("aclovate", "Aclovate"),
            ("actigall", "Actigall"),
            ("actiq", "Actiq"),
            ("adalat_cc", "Adalat CC"),
            ("adderall", "Adderall"),
            ("adderall_xr", "Adderall XR"),
            ("adipex_p", "Adipex-P"),
            ("agrylin", "Agrylin"),
            ("aldactazide", "Aldactazide"),
            ("aldactone", "Aldactone"),
            ("aldara", "Aldara"),
            ("allegra", "Allegra"),
            ("alphagan_p", "Alphagan P"),
            ("altace", "Altace"),
            ("amaryl", "Amaryl"),
            ("ambien", "Ambien"),
            ("ambien_cr", "Ambien CR"),
            ("amerge", "Amerge"),
            ("anafranil", "Anafranil"),
            ("anaprox", "Anaprox"),
            ("antivert", "Antivert"),
            ("aralen", "Aralen"),
            ("arava", "Arava"),
            ("aricept", "Aricept"),
            ("aricept_odt", "Aricept ODT"),
            ("astelin", "Astelin"),
            ("ativan", "Ativan"),
            ("atrovent_nasal spray", "Atrovent Nasal Spray"),
            ("augmentin", "Augmentin"),
            ("augmentin_xr", "Augmentin XR"),
            ("axid", "Axid"),
            ("aygestin", "Aygestin"),
            ("azulfidine", "Azulfidine"),
            ("azulfidine_en_tabs", "Azulfidine EN-TABS"),
            ("bactroban", "Bactroban"),
            ("bentyl", "Bentyl"),
            ("benzac_ac", "Benzac AC"),
            ("benzamycin", "Benzamycin"),
            ("betagan", "Betagan"),
            ("betapace_af", "Betapace AF"),
            ("biaxin", "Biaxin"),
            ("biaxin_xl", "Biaxin XL"),
            ("bleph_10", "Bleph-10"),
            ("bontril", "Bontril"),
            ("brethine", "Brethine"),
            ("brevicon", "Brevicon"),
            ("cafergot", "Cafergot"),
            ("calan", "Calan"),
            ("calan_sr", "Calan SR"),
            ("carafate", "Carafate"),
            ("cardizem", "Cardizem"),
            ("cardizem_cd", "Cardizem CD"),
            ("cardizem_la", "Cardizem LA"),
            ("cardura", "Cardura"),
            ("cataflam", "Cataflam"),
            ("catapres", "Catapres"),
            ("ceftin", "Ceftin"),
            ("cellcept", "Cellcept"),
            ("ciloxan", "Ciloxan"),
            ("cipro", "Cipro"),
            ("claritin", "Claritin"),
            ("cleocin", "Cleocin"),
            ("cleocin_t", "Cleocin T"),
            ("cleocin_vaginal_cream", "Cleocin Vaginal Cream"),
            ("climara", "Climara"),
            ("clinoril", "Clinoril"),
            ("clomid", "Clomid"),
            ("clozaril", "Clozaril"),
            ("colazal", "Colazal"),
            ("colestid", "Colestid"),
            ("condylox", "Condylox"),
            ("copegus", "Copegus"),
            ("cordarone", "Cordarone"),
            ("coreg", "Coreg"),
            ("corgard", "Corgard"),
            ("cortef", "Cortef"),
            ("corzide", "Corzide"),
            ("cosopt", "Cosopt"),
            ("coumadin", "Coumadin"),
            ("cozaar", "Cozaar"),
            ("cutivate", "Cutivate"),
            ("cyclogyl", "Cyclogyl"),
            ("cytomel", "Cytomel"),
            ("cytotec", "Cytotec"),
            ("cytovene", "Cytovene"),
            ("dantrium", "Dantrium"),
            ("daypro", "Daypro"),
            ("ddavp", "Ddavp"),
            ("demadex", "Demadex"),
            ("demerol", "Demerol"),
            ("depakene", "Depakene"),
            ("depakote", "Depakote"),
            ("depakote_er", "Depakote ER"),
            ("depakote_sprinkles", "Depakote SPRINKLES"),
            ("depo_provera", "Depo-PROVERA"),
            ("desogen", "Desogen"),
            ("desowen", "Desowen"),
            ("dexedrine", "Dexedrine"),
            ("dexedrine_spansule", "Dexedrine SPANSULE"),
            ("d.H.E. 45", "D.H.E. 45"),
            ("diabeta", "Diabeta"),
            ("diamox_sequels", "Diamox SEQUELS"),
            ("differin", "Differin"),
            ("diflucan", "Diflucan"),
            ("dilacor_xr", "Dilacor XR"),
            ("dilantin", "Dilantin"),
            ("dilaudid", "Dilaudid"),
            ("diprolene_af", "Diprolene AF"),
            ("diprolene_gel_lotion_oint", "Diprolene gel / lotion / oint"),
            ("ditropan_xl", "Ditropan XL"),
            ("donnatal", "Donnatal"),
            ("drisdol", "Drisdol"),
            ("duoneb", "Duoneb"),
            ("duragesic", "Duragesic"),
            ("dyazide", "Dyazide"),
            ("ec_naprosyn", "Ec-NAPROSYN"),
            ("effexor_xr", "Effexor XR"),
            ("efudex", "Efudex"),
            ("eldepryl", "Eldepryl"),
            ("eldopaque_forte", "Eldopaque FORTE"),
            ("elocon", "Elocon"),
            ("emla", "Emla"),
            ("esgic", "Esgic"),
            ("esgic_plus", "Esgic-PLUS"),
            ("estrace", "Estrace"),
            ("estrostep_fe", "Estrostep FE"),
            ("exelon", "Exelon"),
            ("famvir", "Famvir"),
            ("feldene", "Feldene"),
            ("fioricet", "Fioricet"),
            ("fiorinal", "Fiorinal"),
            ("flagyl", "Flagyl"),
            ("flagyl_375", "Flagyl 375"),
            ("flagyl_er", "Flagyl ER"),
            ("flarex", "Flarex"),
            ("flexeril", "Flexeril"),
            ("flomax", "Flomax"),
            ("flonase", "Flonase"),
            ("flumadine", "Flumadine"),
            ("fml", "Fml"),
            ("focalin", "Focalin"),
            ("foltx", "Foltx"),
            ("fosamax", "Fosamax"),
            ("glucophage", "Glucophage"),
            ("glucophage_xr", "Glucophage XR"),
            ("glucotrol", "Glucotrol"),
            ("glucovance", "Glucovance"),
            ("glynase", "Glynase"),
            ("halcion", "Halcion"),
            ("hydrea", "Hydrea"),
            ("hyzaar", "Hyzaar"),
            ("imdur", "Imdur"),
            ("imitrex", "Imitrex"),
            ("imuran", "Imuran"),
            ("inderal_la", "Inderal LA"),
            ("inspra", "Inspra"),
            ("isoptin_sr", "Isoptin SR"),
            ("isordil", "Isordil"),
            ("keflex", "Keflex"),
            ("keppra", "Keppra"),
            ("kerlone", "Kerlone"),
            ("klaron", "Klaron"),
            ("klonopin", "Klonopin"),
            ("k_lor_20", "K-LOR 20"),
            ("k_tab", "K-TAB"),
            ("kytril", "Kytril"),
            ("lac_hydrin", "Lac-HYDRIN"),
            ("lamictal", "Lamictal"),
            ("lamisil", "Lamisil"),
            ("lanoxin", "Lanoxin"),
            ("lasix", "Lasix"),
            ("levbid", "Levbid"),
            ("levsin", "Levsin"),
            ("lithobid", "Lithobid"),
            ("lo_OVRAL", "Lo / OVRAL"),
            ("locoid", "Locoid"),
            ("loestrin_1.5_30", "Loestrin 1.5 / 30"),
            ("loestrin_fe_1_20", "Loestrin FE 1 / 20"),
            ("loestrin_fe_1.5_30", "Loestrin FE 1.5 / 30"),
            ("lomotil", "Lomotil"),
            ("lopid", "Lopid"),
            ("lopressor", "Lopressor"),
            ("loprox", "Loprox"),
            ("lorcet", "Lorcet"),
            ("lortab", "Lortab"),
            ("lotensin", "Lotensin"),
            ("lotensin_hct", "Lotensin HCT"),
            ("lotrel", "Lotrel"),
            ("loxitane", "Loxitane"),
            ("luride", "Luride"),
            ("luride_lozi_tabs", "Luride LOZI-TABS"),
            ("lustra", "Lustra"),
            ("macrobid", "Macrobid"),
            ("macrodantin", "Macrodantin"),
            ("mavik", "Mavik"),
            ("maxidone", "Maxidone"),
            ("maxitrol", "Maxitrol"),
            ("maxzide", "Maxzide"),
            ("maxzide_25", "Maxzide-25"),
            ("medrol", "Medrol"),
            ("megace", "Megace"),
            ("mestinon", "Mestinon"),
            ("metadate_er", "Metadate ER"),
            ("metaglip", "Metaglip"),
            ("metrocream", "Metrocream"),
            ("metrolotion", "Metrolotion"),
            ("metrogel_vaginal", "Metrogel-VAGINAL"),
            ("mevacor", "Mevacor"),
            ("miacalcin_nasal_spray", "Miacalcin nasal spray"),
            ("midrin", "Midrin"),
            ("minipress", "Minipress"),
            ("minocin", "Minocin"),
            ("miralax", "Miralax"),
            ("mirapex", "Mirapex"),
            ("mircette", "Mircette"),
            ("mobic", "Mobic"),
            ("modicon", "Modicon"),
            ("monodox", "Monodox"),
            ("motrin", "Motrin"),
            ("ms_contin", "Ms CONTIN"),
            ("myambutol", "Myambutol"),
            ("mycelex", "Mycelex"),
            ("mysoline", "Mysoline"),
            ("naprosyn", "Naprosyn"),
            ("navane", "Navane"),
            ("neo_synephrine", "Neo-SYNEPHRINE"),
            ("neoral", "Neoral"),
            ("neosporin", "Neosporin"),
            ("neurontin", "Neurontin"),
            ("nimotop", "Nimotop"),
            ("niravam", "Niravam"),
            ("nitro_dur", "Nitro-DUR"),
            ("nizoral_shampoo", "Nizoral SHAMPOO"),
            ("nordette", "Nordette"),
            ("norinyl_1_35", "Norinyl 1+35"),
            ("norinyl_1_50", "Norinyl 1+50"),
            ("norpace", "Norpace"),
            ("norpramin", "Norpramin"),
            ("nor_qd", "Nor-QD"),
            ("norvasc", "Norvasc"),
            ("nulytely", "Nulytely"),
            ("ocuflox", "Ocuflox"),
            ("olux", "Olux"),
            ("opana", "Opana"),
            ("optipranolol", "Optipranolol"),
            ("orapred", "Orapred"),
            ("ortho_cept", "Ortho-CEPT"),
            ("ortho_cyclen", "Ortho-CYCLEN"),
            ("ortho_micronor", "Ortho MICRONOR"),
            ("ortho_novum_1_35", "Ortho-NOVUM 1 / 35"),
            ("ortho_novum_7_7_7", "Ortho-NOVUM 7 / 7 / 7"),
            ("ortho_tri_cyclen", "Ortho TRI-CYCLEN"),
            ("ovcon_35", "Ovcon 35"),
            ("ovide", "Ovide"),
            ("oxandrin", "Oxandrin"),
            ("pacerone", "Pacerone"),
            ("pamelor", "Pamelor"),
            ("pamine", "Pamine"),
            ("pamine_forte", "Pamine FORTE"),
            ("parafon_forte_dsc", "Parafon FORTE DSC"),
            ("parcopa", "Parcopa"),
            ("parlodel", "Parlodel"),
            ("parnate", "Parnate"),
            ("paxil", "Paxil"),
            ("paxil_cr", "Paxil CR"),
            ("pediapred", "Pediapred"),
            ("pepcid", "Pepcid"),
            ("percocet", "Percocet"),
            ("percodan", "Percodan"),
            ("peridex", "Peridex"),
            ("periostat", "Periostat"),
            ("persantine", "Persantine"),
            ("phoslo", "Phoslo"),
            ("plaquenil", "Plaquenil"),
            ("plexion", "Plexion"),
            ("polytrim", "Polytrim"),
            ("ponstel", "Ponstel"),
            ("pravachol", "Pravachol"),
            ("pred_forte", "Pred FORTE"),
            ("prelone", "Prelone"),
            ("prevacid", "Prevacid"),
            ("prevacid_solutabs", "Prevacid SOLUTABS"),
            ("prilosec", "Prilosec"),
            ("prinivil", "Prinivil"),
            ("prinzide", "Prinzide"),
            ("procardia_xl", "Procardia XL"),
            ("proctocort", "Proctocort"),
            ("proctocream_hc_2.5", "Proctocream-HC 2.5%"),
            ("proscar", "Proscar"),
            ("prosom", "Prosom"),
            ("protonix", "Protonix"),
            ("provera", "Provera"),
            ("prozac", "Prozac"),
            ("prozac_weekly", "Prozac WEEKLY"),
            ("pulmicort_respules", "Pulmicort RESPULES"),
            ("pyridium", "Pyridium"),
            ("questran", "Questran / QUESTRAN LIGHT"),
            ("razadyne", "Razadyne"),
            ("razadyne_er", "Razadyne ER"),
            ("rebetol", "Rebetol"),
            ("reglan", "Reglan"),
            ("remeron", "Remeron"),
            ("remeron_soltab", "Remeron SOLTAB"),
            ("requip", "Requip"),
            ("restoril", "Restoril"),
            ("retin_a", "Retin-A"),
            ("retrovir", "Retrovir"),
            ("revia", "Revia"),
            ("rifadin", "Rifadin"),
            ("risperdal", "Risperdal"),
            ("risperdal_m_tab", "Risperdal M-TAB"),
            ("ritalin", "Ritalin"),
            ("ritalin_sr", "Ritalin-SR"),
            ("robaxin", "Robaxin"),
            ("rocaltrol", "Rocaltrol"),
            ("rowasa", "Rowasa"),
            ("roxicodone", "Roxicodone"),
            ("rythmol", "Rythmol"),
            ("rythmol_sr", "Rythmol SR"),
            ("salagen", "Salagen"),
            ("sanctura", "Sanctura"),
            ("seasonale", "Seasonale"),
            ("sectral", "Sectral"),
            ("selsun", "Selsun"),
            ("septra", "Septra"),
            ("septra_ds", "Septra DS"),
            ("silvadene", "Silvadene"),
            ("sinemet", "Sinemet"),
            ("sinemet_cr", "Sinemet CR"),
            ("skelaxin", "Skelaxin"),
            ("soma", "Soma"),
            ("sonata", "Sonata"),
            ("sporanox", "Sporanox"),
            ("starlix", "Starlix"),
            ("sular", "Sular"),
            ("synthroid", "Synthroid"),
            ("tambocor", "Tambocor"),
            ("tapazole", "Tapazole"),
            ("tarka", "Tarka"),
            ("tegretol", "Tegretol"),
            ("tegretol_xr", "Tegretol XR"),
            ("temovate", "Temovate"),
            ("tenex", "Tenex"),
            ("tenoretic", "Tenoretic"),
            ("tenormin", "Tenormin"),
            ("tenuate", "Tenuate"),
            ("terazol_3", "Terazol 3"),
            ("terazol_7", "Terazol 7"),
            ("tessalon", "Tessalon"),
            ("tiazac", "Tiazac"),
            ("tigan_caps", "Tigan caps"),
            ("timoptic", "Timoptic"),
            ("timoptic_ocudose", "Timoptic OCUDOSE"),
            ("timoptic_xe", "Timoptic-XE"),
            ("tobradex", "Tobradex"),
            ("tobrex", "Tobrex"),
            ("tofranil", "Tofranil"),
            ("tofranil_pm", "Tofranil PM"),
            ("tolectin", "Tolectin"),
            ("topamax", "Topamax"),
            ("topicort", "Topicort"),
            ("toprol_xl", "Toprol-XL"),
            ("tranxene_t_tab", "Tranxene T-TAB"),
            ("triaz", "Triaz"),
            ("trileptal", "Trileptal"),
            ("tri_norinyl", "Tri-NORINYL"),
            ("trusopt", "Trusopt"),
            ("tussionex", "Tussionex"),
            ("tylenol", "Tylenol WITH CODEINE"),
            ("tylox", "Tylox"),
            ("ultram", "Ultram"),
            ("ultravate", "Ultravate"),
            ("uniretic", "Uniretic"),
            ("univasc", "Univasc"),
            ("urso", "Urso"),
            ("valium", "Valium"),
            ("valtrex", "Valtrex"),
            ("vaseretic", "Vaseretic"),
            ("vasotec", "Vasotec"),
            ("venlafaxine_er", "Venlafaxine ER"),
            ("verelan_pm", "Verelan PM"),
            ("vibramycin", "Vibramycin"),
            ("vicodin", "Vicodin"),
            ("vicodin_es", "Vicodin ES"),
            ("vicoprofen", "Vicoprofen"),
            ("videx_ec", "Videx EC"),
            ("viroptic", "Viroptic"),
            ("vistaril", "Vistaril"),
            ("vivactil", "Vivactil"),
            ("voltaren_ophthalmic", "Voltaren OPHTHALMIC"),
            ("voltaren_xr", "Voltaren-XR"),
            ("vospire_er", "Vospire ER"),
            ("wellbutrin", "Wellbutrin"),
            ("wellbutrin_sr", "Wellbutrin SR"),
            ("wellbutrin_xl", "Wellbutrin XL"),
            ("westcort", "Westcort"),
            ("xanax", "Xanax"),
            ("xanax_xr", "Xanax XR"),
            ("xyzal", "Xyzal"),
            ("yasmin", "Yasmin"),
            ("yaz", "Yaz"),
            ("zanaflex", "Zanaflex"),
            ("zantac", "Zantac"),
            ("zarontin", "Zarontin"),
            ("zaroxolyn", "Zaroxolyn"),
            ("zegerid", "Zegerid"),
            ("zerit", "Zerit"),
            ("zestoretic", "Zestoretic"),
            ("zestril", "Zestril"),
            ("ziac", "Ziac"),
            ("zithromax", "Zithromax"),
            ("zocor", "Zocor"),
            ("zofran", "Zofran"),
            ("zoloft", "Zoloft"),
            ("zonegran", "Zonegran"),
            ("zovirax", "Zovirax"),
            ("zyban", "Zyban"),
            ("zyloprim", "Zyloprim"),
            ("zyrtec", "Zyrtec"),
        ],
        string="Médicaments #3",
    )

    membre_assoc_comite = fields.Selection(
        selection=[("oui", "Oui"), ("non", "Non")],
        string="Membre d'une association ou comité",
    )

    membre_assoc_comite_detail = fields.Text(string="Laquelle")

    motivations_implication = fields.Text(string="Motivations à s'impliquer")

    perspective = fields.Char()

    preferences = fields.Selection(
        selection=[
            ("recherche", "Recherche"),
            ("gouvernance", "Gouvernance"),
            ("tables_travail", "Tables de travail"),
            ("comites", "Comités"),
            ("milieux_soins", "Milieux de soins"),
            ("enseignement", "Enseignement"),
            ("interets_autre", "Autre"),
        ],
        string="Préférences",
    )

    preferences_autre = fields.Text(string="Autres préférences")

    preneur_decisions = fields.Text(string="Preneur de décisions")

    prob_sant = fields.Many2one(
        comodel_name="ceppp.suite_crm.maladie",
        string="Problématiques de santé",
    )

    prob_sant_pa = fields.Many2one(
        comodel_name="ceppp.suite_crm.maladie",
        string="Problématiques de santé",
    )

    professionnels_sante = fields.Char(string="Professionnels de la santé")

    rel_patient = fields.Selection(
        selection=[
            ("parent", "Parent"),
            ("enfant", "Enfant"),
            ("conjoint", "Conjoint(e)"),
            ("famille_elargie", "Famille élargie"),
            ("autre", "Autre"),
        ],
        string="Relation avec le patient",
    )

    role_pp = fields.Selection(
        selection=[
            ("coach", "Coach"),
            ("co_chercheur", "Co-chercheur"),
            ("formateur", "Formateur"),
            ("accompagnateur", "Accompagnateur"),
            ("aviseur", "Aviseur"),
        ],
        string="Rôle",
    )
