{
    "name": "Ceppp Suite Crm",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "SantéLibre",
    "license": "AGPL-3",
    "website": "https://santelibre.ca",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/ceppp_suite_crm_commentaires_recruteur.xml",
        "views/ceppp_suite_crm_entrevues.xml",
        "views/ceppp_suite_crm_exp_patient_partenaire.xml",
        "views/ceppp_suite_crm_formation.xml",
        "views/ceppp_suite_crm_partenariats.xml",
        "views/ceppp_suite_crm_patients.xml",
        "views/ceppp_suite_crm_perspective_patient.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
