{
    "name": "Ceppp Suite Crm",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "SantéLibre",
    "license": "AGPL-3",
    "website": "https://santelibre.ca",
    "application": True,
    "data": [
        "security/ir.model.access.csv",
        "views/ceppp_suite_crm_assistance_mob.xml",
        "data/ceppp_suite_crm_assistance_mob.xml",
        "views/ceppp_suite_crm_chapitre_maladie.xml",
        "data/ceppp_suite_crm_chapitre_maladie.xml",
        "data/ceppp_suite_crm_maladie.xml",
        "views/ceppp_suite_crm_commentaires_recruteur.xml",
        "views/ceppp_suite_crm_competences_pp.xml",
        "data/ceppp_suite_crm_competences_pp.xml",
        "views/ceppp_suite_crm_competences_ppc.xml",
        "data/ceppp_suite_crm_competences_ppc.xml",
        "views/ceppp_suite_crm_competences_pr.xml",
        "data/ceppp_suite_crm_competences_pr.xml",
        "views/ceppp_suite_crm_deplacements.xml",
        "data/ceppp_suite_crm_deplacements.xml",
        "views/ceppp_suite_crm_disponibilites.xml",
        "data/ceppp_suite_crm_disponibilites.xml",
        "views/ceppp_suite_crm_domaine_soin_pa.xml",
        "data/ceppp_suite_crm_domaine_soin_pa.xml",
        "views/ceppp_suite_crm_emploi_perso.xml",
        "data/ceppp_suite_crm_emploi_perso.xml",
        "views/ceppp_suite_crm_entrevues.xml",
        "views/ceppp_suite_crm_exp_patient_partenaire.xml",
        "views/ceppp_suite_crm_formation.xml",
        "views/ceppp_suite_crm_habiletes_pp.xml",
        "data/ceppp_suite_crm_habiletes_pp.xml",
        "views/ceppp_suite_crm_hopital.xml",
        "views/ceppp_suite_crm_langue_parlee.xml",
        "data/ceppp_suite_crm_langue_parlee.xml",
        "views/ceppp_suite_crm_maladie.xml",
        "views/ceppp_suite_crm_med_2.xml",
        "data/ceppp_suite_crm_med_2.xml",
        "views/ceppp_suite_crm_partenariats.xml",
        "views/ceppp_suite_crm_patients.xml",
        "views/ceppp_suite_crm_perspective_patient.xml",
        "views/ceppp_suite_crm_preferences.xml",
        "data/ceppp_suite_crm_preferences.xml",
        "views/ceppp_suite_crm_region_admin.xml",
        "data/ceppp_suite_crm_region_admin.xml",
        "data/ceppp_suite_crm_hopital.xml",
        "views/ceppp_suite_crm_role_pp.xml",
        "data/ceppp_suite_crm_role_pp.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
