{
    "name": "Ceppp Patient Partenaire",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "SantéLibre",
    "license": "AGPL-3",
    "website": "https://santelibre.ca",
    "application": True,
    "depends": [
        "contacts",
        "mail",
        "portal",
    ],
    "data": [
        "security/ceppp_patient_partenaire.xml",
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "views/ceppp_patient_partenaire_templates.xml",
        "views/ceppp_chapitre_maladie.xml",
        "data/ceppp_chapitre_maladie.xml",
        "views/ceppp_competence.xml",
        "views/ceppp_disponibilite.xml",
        "data/ceppp_disponibilite.xml",
        "data/ceppp_competence.xml",
        "views/ceppp_formation.xml",
        "views/ceppp_formation_titre.xml",
        "data/ceppp_formation_titre.xml",
        "views/ceppp_implication.xml",
        "views/ceppp_implication_domaine.xml",
        "data/ceppp_implication_domaine.xml",
        "views/ceppp_implication_role.xml",
        "data/ceppp_implication_role.xml",
        "views/ceppp_langue.xml",
        "data/ceppp_langue.xml",
        "views/ceppp_maladie.xml",
        "data/ceppp_maladie.xml",
        "views/ceppp_maladie_personne_affectee.xml",
        "views/ceppp_mode_communication_privilegie.xml",
        "data/ceppp_mode_communication_privilegie.xml",
        "views/ceppp_occupation.xml",
        "data/ceppp_occupation.xml",
        "views/ceppp_patient.xml",
        "views/ceppp_recruteur.xml",
        "views/ceppp_relation_proche.xml",
        "data/ceppp_relation_proche.xml",
        "wizards/create_member_views.xml",
        "views/menu.xml",
        "data/ir_attachment.xml",
        "views/portal_templates.xml",
    ],
    "installable": True,
    "post_init_hook": "post_init_hook",
}
